#!/bin/bash

# docker build --target slim_builder --tag $DOCKER_REPO/qemu-raspbian:slim_builder .
docker build --target buster_slim --tag $DOCKER_REPO/qemu-raspbian:buster_slim .

docker tag buster_slim $DOCKER_REPO:slim
docker push $DOCKER_REPO:slim

# docker build --target buster_latest_builder --tag $DOCKER_REPO/qemu-raspbian:buster_latest_builder .
docker build --target buster_latest --tag $DOCKER_REPO/qemu-raspbian:buster_latest .

docker tag buster_latest $DOCKER_REPO:latest
docker push $DOCKER_REPO:latest
