name: choonkiatlee/qemu-raspbian:buster-slim

on:
  push:
    branches: [ master ]
    paths:
    - 'buster_slim/Dockerfile'
  pull_request:
    branches: [ master ]
    paths:
    - 'buster_slim/Dockerfile'

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install QEMU
      run: sudo apt-get update && sudo apt-get install qemu-user-static qemu binfmt-support
    - name: Build Buster Slim
      run: docker build -f buster_slim/Dockerfile --tag choonkiatlee/qemu-raspbian:buster-slim --tag choonkiatlee/qemu-raspbian:slim .
    - name: Login
      run: docker login --username=${{ secrets.DOCKER_USERNAME }} --password=${{ secrets.DOCKER_PASSWORD }}
    - name: Publish Docker
      run: docker push choonkiatlee/qemu-raspbian:buster-slim
    - name: Publish Docker
      run: docker push choonkiatlee/qemu-raspbian:slim
