name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install QEMU
      run: sudo apt-get update && sudo apt-get install qemu-user-static qemu binfmt-support
    - name: Publish Docker
      uses: elgohr/Publish-Docker-Github-Action@2.14
      with:
        name: choonkiatlee/qemu-raspbian
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        dockerfile: buster_slim/Dockerfile
        tags: slim,buster-slim    
